### ISSUE TITLE
UCloud库文件上传后有一个Notice

### ISSUE THREAD

**Issue by xiao91** [phalapi/phalapi-library#2]
如下Notice:
<br />
<b>Notice</b>:  A non well formed numeric value encountered in <b>E:\php\XAMPP\xampp\htdocs\Sky\Library\UCloud\Lite.php</b> 
on line <b>140</b><br />

代码：

  ```
     /**
      * 设置文件名称 不包括 文件路径
      *
      * 生成(从2000-01-01 00:00:00 到现在的秒数+微秒+四位随机)
      */
  private function setFileName(){
        if(empty($this->file_name)){
            $tmp_name = sprintf('%010d',time() - 946656000)
                             . sprintf('%03d', microtime() * 1000)
                             . sprintf('%04d', mt_rand(0,9999));
         }else{
             $tmp_name = $this->file_name;
         }
             $this->file_name = $tmp_name . '.' . $this->ext;
    }
```
原代码中的<br/>
<b> . sprintf('%03d', microtime() * 1000)</b><br/>
这一行，调用了microtime()，microtime(get_as_float)函数有一个可选的参数，默认是false，如果是false返回的是字符串，是true返回的是浮点数。

这样microtime(true)设置true后，不会有提示了，Android端在上传文件后解析json数据时，就不会报错了。

**Comment by phalapi** [comment]
感谢反馈，已修正。（PS：github提交了对应的注释，会自动关闭相应的issue，功能真贴心）
